// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vdata_comparator.cpp"
#include "Vdata_comparator___024root__0.cpp"
#include "Vdata_comparator__Trace__0.cpp"
#include "Vdata_comparator___024root__Slow.cpp"
#include "Vdata_comparator___024root__0__Slow.cpp"
#include "Vdata_comparator__Syms__Slow.cpp"
#include "Vdata_comparator__Trace__0__Slow.cpp"
#include "Vdata_comparator__TraceDecls__0__Slow.cpp"
